#!/bin/bash
cd /(PATH OF YOUR STEAM INSTALLATION)/Steam/steamapps/compatdata/322170/pfx
PROTON_LOG=1 STEAM_COMPAT_CLIENT_INSTALL_PATH='/(PATH OF YOUR STEAM INSTALLATION)/Steam' STEAM_COMPAT_DATA_PATH='/(PATH OF YOUR STEAM INSTALLATION)/Steam/steamapps/compatdata/322170' WINEPREFIX=$PWD '/(PATH OF YOUR STEAM INSTALLATION)/Steam/steamapps/common/(YOUR PROTON VERSION)/proton' run ./drive_c/(ADDRESS OF THE MEGA HACK INSTALL)/MegaHackPro.exe
